import { z } from 'zod'

export const tradeSchema = z.object({
  date: z.string().min(1, 'Tanggal wajib diisi'),
  time: z.string().min(1, 'Waktu wajib diisi'),
  market: z.string().min(1, 'Market wajib diisi'),
  pair: z.string().min(1, 'Pair/Asset wajib diisi'),
  timeframe: z.string().min(1, 'Timeframe wajib diisi'),
  session: z.string().min(1, 'Session wajib diisi'),
  tradeType: z.string().min(1, 'Tipe Trade wajib diisi'),
  marketCondition: z.string().min(1, 'Kondisi Market wajib diisi'),
  marketBias: z.string().optional(),
  strategy: z.string().optional(),
  setup: z.string().min(1, 'Setup wajib diisi'),
  technicalConfirmation: z.string().optional(),
  fundamentalConfirmation: z.string().optional(),
  entryReason: z.string().optional(),
  entryPrice: z.string().optional(),
  stopLoss: z.string().optional(),
  takeProfit: z.string().optional(),
  riskPercent: z.string().optional(),
  rrRatio: z.string().optional(),
  positionSize: z.string().optional(),
  entryOnPlan: z.boolean().optional(),
  slippage: z.string().optional(),
  planChange: z.string().optional(),
  tradeManagement: z.string().optional(),
  emotionBefore: z.string().optional(),
  emotionalDisruption: z.string().optional(),
  confidence: z.number().min(1),
  discipline: z.number().min(1),
  exitPrice: z.string().optional(),
  profitLoss: z.string().optional(),
  result: z.string().min(1, 'Result wajib diisi'),
  actualRR: z.string().optional(),
  whatWentRight: z.string().optional(),
  mistakes: z.string().optional(),
  validSetup: z.boolean().optional(),
  entryTiming: z.string().optional(),
  lesson: z.string().optional(),
  notes: z.string().min(1, 'Notes wajib diisi'),
  tags: z.array(z.string()).optional().default([]),
  improvement: z.string().optional(),
  rulesToTighten: z.string().optional(),
  actionPlan: z.string().optional(),
})

export type TradeFormInput = z.input<typeof tradeSchema>
export type TradeFormValues = z.infer<typeof tradeSchema>
