/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardTradeIndexRouteImport } from './routes/dashboard/trade.index'
import { Route as DashboardTradeQuickAddRouteImport } from './routes/dashboard/trade.quick-add'
import { Route as DashboardTradeNewRouteImport } from './routes/dashboard/trade.new'
import { Route as DashboardSettingsProfileRouteImport } from './routes/dashboard/settings.profile'
import { Route as DashboardSettingsAppearanceRouteImport } from './routes/dashboard/settings.appearance'
import { Route as DashboardTradeTradeIdEditRouteImport } from './routes/dashboard/trade.$tradeId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTradeIndexRoute = DashboardTradeIndexRouteImport.update({
  id: '/trade/',
  path: '/trade/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTradeQuickAddRoute = DashboardTradeQuickAddRouteImport.update({
  id: '/trade/quick-add',
  path: '/trade/quick-add',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTradeNewRoute = DashboardTradeNewRouteImport.update({
  id: '/trade/new',
  path: '/trade/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsAppearanceRoute =
  DashboardSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardTradeTradeIdEditRoute =
  DashboardTradeTradeIdEditRouteImport.update({
    id: '/trade/$tradeId/edit',
    path: '/trade/$tradeId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/trade/new': typeof DashboardTradeNewRoute
  '/dashboard/trade/quick-add': typeof DashboardTradeQuickAddRoute
  '/dashboard/trade/': typeof DashboardTradeIndexRoute
  '/dashboard/trade/$tradeId/edit': typeof DashboardTradeTradeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/trade/new': typeof DashboardTradeNewRoute
  '/dashboard/trade/quick-add': typeof DashboardTradeQuickAddRoute
  '/dashboard/trade': typeof DashboardTradeIndexRoute
  '/dashboard/trade/$tradeId/edit': typeof DashboardTradeTradeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/appearance': typeof DashboardSettingsAppearanceRoute
  '/dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/dashboard/trade/new': typeof DashboardTradeNewRoute
  '/dashboard/trade/quick-add': typeof DashboardTradeQuickAddRoute
  '/dashboard/trade/': typeof DashboardTradeIndexRoute
  '/dashboard/trade/$tradeId/edit': typeof DashboardTradeTradeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/profile'
    | '/dashboard/trade/new'
    | '/dashboard/trade/quick-add'
    | '/dashboard/trade/'
    | '/dashboard/trade/$tradeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/profile'
    | '/dashboard/trade/new'
    | '/dashboard/trade/quick-add'
    | '/dashboard/trade'
    | '/dashboard/trade/$tradeId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/settings/appearance'
    | '/dashboard/settings/profile'
    | '/dashboard/trade/new'
    | '/dashboard/trade/quick-add'
    | '/dashboard/trade/'
    | '/dashboard/trade/$tradeId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trade/': {
      id: '/dashboard/trade/'
      path: '/trade'
      fullPath: '/dashboard/trade/'
      preLoaderRoute: typeof DashboardTradeIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trade/quick-add': {
      id: '/dashboard/trade/quick-add'
      path: '/trade/quick-add'
      fullPath: '/dashboard/trade/quick-add'
      preLoaderRoute: typeof DashboardTradeQuickAddRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trade/new': {
      id: '/dashboard/trade/new'
      path: '/trade/new'
      fullPath: '/dashboard/trade/new'
      preLoaderRoute: typeof DashboardTradeNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/profile': {
      id: '/dashboard/settings/profile'
      path: '/profile'
      fullPath: '/dashboard/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/appearance': {
      id: '/dashboard/settings/appearance'
      path: '/appearance'
      fullPath: '/dashboard/settings/appearance'
      preLoaderRoute: typeof DashboardSettingsAppearanceRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/trade/$tradeId/edit': {
      id: '/dashboard/trade/$tradeId/edit'
      path: '/trade/$tradeId/edit'
      fullPath: '/dashboard/trade/$tradeId/edit'
      preLoaderRoute: typeof DashboardTradeTradeIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardSettingsRouteChildren {
  DashboardSettingsAppearanceRoute: typeof DashboardSettingsAppearanceRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsAppearanceRoute: DashboardSettingsAppearanceRoute,
  DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTradeNewRoute: typeof DashboardTradeNewRoute
  DashboardTradeQuickAddRoute: typeof DashboardTradeQuickAddRoute
  DashboardTradeIndexRoute: typeof DashboardTradeIndexRoute
  DashboardTradeTradeIdEditRoute: typeof DashboardTradeTradeIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTradeNewRoute: DashboardTradeNewRoute,
  DashboardTradeQuickAddRoute: DashboardTradeQuickAddRoute,
  DashboardTradeIndexRoute: DashboardTradeIndexRoute,
  DashboardTradeTradeIdEditRoute: DashboardTradeTradeIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
