/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTradeIndexRouteImport } from './routes/dashboard/trade.index'
import { Route as DashboardTradeQuickAddRouteImport } from './routes/dashboard/trade.quick-add'
import { Route as DashboardTradeNewRouteImport } from './routes/dashboard/trade.new'
import { Route as DashboardTradeTradeIdEditRouteImport } from './routes/dashboard/trade.$tradeId.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTradeIndexRoute = DashboardTradeIndexRouteImport.update({
  id: '/trade/',
  path: '/trade/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTradeQuickAddRoute = DashboardTradeQuickAddRouteImport.update({
  id: '/trade/quick-add',
  path: '/trade/quick-add',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTradeNewRoute = DashboardTradeNewRouteImport.update({
  id: '/trade/new',
  path: '/trade/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTradeTradeIdEditRoute =
  DashboardTradeTradeIdEditRouteImport.update({
    id: '/trade/$tradeId/edit',
    path: '/trade/$tradeId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/settings': typeof SettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/trade/new': typeof DashboardTradeNewRoute
  '/dashboard/trade/quick-add': typeof DashboardTradeQuickAddRoute
  '/dashboard/trade/': typeof DashboardTradeIndexRoute
  '/dashboard/trade/$tradeId/edit': typeof DashboardTradeTradeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/trade/new': typeof DashboardTradeNewRoute
  '/dashboard/trade/quick-add': typeof DashboardTradeQuickAddRoute
  '/dashboard/trade': typeof DashboardTradeIndexRoute
  '/dashboard/trade/$tradeId/edit': typeof DashboardTradeTradeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/settings': typeof SettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/trade/new': typeof DashboardTradeNewRoute
  '/dashboard/trade/quick-add': typeof DashboardTradeQuickAddRoute
  '/dashboard/trade/': typeof DashboardTradeIndexRoute
  '/dashboard/trade/$tradeId/edit': typeof DashboardTradeTradeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/dashboard/'
    | '/dashboard/trade/new'
    | '/dashboard/trade/quick-add'
    | '/dashboard/trade/'
    | '/dashboard/trade/$tradeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/dashboard'
    | '/dashboard/trade/new'
    | '/dashboard/trade/quick-add'
    | '/dashboard/trade'
    | '/dashboard/trade/$tradeId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/settings'
    | '/dashboard/'
    | '/dashboard/trade/new'
    | '/dashboard/trade/quick-add'
    | '/dashboard/trade/'
    | '/dashboard/trade/$tradeId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trade/': {
      id: '/dashboard/trade/'
      path: '/trade'
      fullPath: '/dashboard/trade/'
      preLoaderRoute: typeof DashboardTradeIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trade/quick-add': {
      id: '/dashboard/trade/quick-add'
      path: '/trade/quick-add'
      fullPath: '/dashboard/trade/quick-add'
      preLoaderRoute: typeof DashboardTradeQuickAddRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trade/new': {
      id: '/dashboard/trade/new'
      path: '/trade/new'
      fullPath: '/dashboard/trade/new'
      preLoaderRoute: typeof DashboardTradeNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trade/$tradeId/edit': {
      id: '/dashboard/trade/$tradeId/edit'
      path: '/trade/$tradeId/edit'
      fullPath: '/dashboard/trade/$tradeId/edit'
      preLoaderRoute: typeof DashboardTradeTradeIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTradeNewRoute: typeof DashboardTradeNewRoute
  DashboardTradeQuickAddRoute: typeof DashboardTradeQuickAddRoute
  DashboardTradeIndexRoute: typeof DashboardTradeIndexRoute
  DashboardTradeTradeIdEditRoute: typeof DashboardTradeTradeIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTradeNewRoute: DashboardTradeNewRoute,
  DashboardTradeQuickAddRoute: DashboardTradeQuickAddRoute,
  DashboardTradeIndexRoute: DashboardTradeIndexRoute,
  DashboardTradeTradeIdEditRoute: DashboardTradeTradeIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
